# -*- coding: utf-8 -*-
"""kpi_crossformer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Iomn2GCBf67PcPI5Ho4pvtlpaUiWVubw

# 매장 KPI 예측 모델 — KPICrossformer
**캡스톤 프로젝트 | 2026-05**

---

## 개요
시뮬레이터로 생성한 매장 구매 이벤트 데이터를 기반으로,  
**다음 날(구역 × 시간대 × 고객군)별 구매수와 체류시간**을 예측하고  
5가지 KPI를 산출하는 Crossformer 모델입니다.

### 예측 대상 KPI
| 번호 | 지표명 | 계산 방식 |
|------|--------|-----------|
| #2 | 전체 구매전환율 | 전체 구매수 합산 (proxy) |
| #3 | 구역별 평균 체류시간 | dwell_head 직접 예측 |
| #5 | 고객군별 구매전환율 | 고객군 차원 분리 예측 |
| #7 | 체류 대비 전환 효율 | zone_buy / zone_dwell (파생) |
| #8 | 비효율 구역 지수 | norm(체류) × (1 − norm(전환)) (파생) |

### 핵심 변경점 (원본 PurchaseGridTransformer 대비)
| 항목 | 원본 | 본 모델 |
|------|------|---------|
| Grid 차원 | 구역 × 시간대 [Z, T] | 구역 × 시간대 × 고객군 [Z, T, C] |
| 토큰 수 | 84개 | **336개** (7 × 12 × 4) |
| 모델 구조 | SpaceTime Attention | **Crossformer** (2-Stage Attention) |
| 예측 타겟 | 구매수 1가지 | 구매수 + 체류시간 **2가지 동시** |

## 0. 환경 설정
"""

# 필수 패키지 설치 (Colab 기본 환경에 없는 것만)
!pip install -q scipy

import math
import random
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from pathlib import Path
from torch.utils.data import Dataset, DataLoader
from scipy.stats import spearmanr
import matplotlib.pyplot as plt
import matplotlib

# 한글 폰트가 없는 환경에서도 차트가 깨지지 않도록 기본 폰트 지정
matplotlib.rcParams['font.family'] = 'DejaVu Sans'

print(f"PyTorch: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Device: {device}")

"""## 데이터 업로드

아래 두 가지 방법 중 하나를 선택하세요.

**방법 A — Google Drive 마운트** (반복 실행 시 권장)
- 드라이브에 `캡스톤/model/data/` 폴더를 만들어두고 방법 A 셀을 실행

**방법 B — 직접 업로드** (기본값, 처음 실행 시)
- 방법 B 셀을 실행하면 파일 선택 창이 열림

필요한 CSV 파일:
- `batch_purchases (1).csv` ← 메인 학습 데이터
- `batch_zone_kpi (1).csv` ← 구역 KPI 검증용
"""

# ── 방법 A: Google Drive 마운트 ───────────────────────────────
# Drive의 '캡스톤/model/data/' 경로에 CSV가 있을 때 사용
# 아래 주석을 해제해서 실행하세요

# from google.colab import drive
# drive.mount('/content/drive')
# DATA_DIR = Path('/content/drive/MyDrive/캡스톤/model/data')

# ── 방법 B: 직접 업로드 (기본값) ────────────────────────────
from google.colab import files

DATA_DIR = Path('/content/data')
DATA_DIR.mkdir(exist_ok=True)

print("CSV 파일을 업로드하세요:")
print("  - batch_purchases (1).csv")
print("  - batch_zone_kpi (1).csv")
uploaded = files.upload()   # 파일 선택 창 열림

# 업로드된 파일을 DATA_DIR에 저장
for fname, data in uploaded.items():
    save_path = DATA_DIR / fname
    save_path.write_bytes(data)
    print(f"  저장 완료: {save_path}")

"""## CFG 설정

모든 하이퍼파라미터를 한 곳에 모아 실험 재현성을 확보합니다.

## 🔧 수정사항 — CFG: batch_size · epochs

### 기존 문제
- **batch_size=32**: 학습 샘플이 79개뿐이라 에폭당 배치가 **2~3개**밖에 안 됨.  
  배치가 너무 크면 그래디언트 업데이트 횟수가 적어 학습 신호가 부족하고 방향이 불안정함.
- **epochs=200**: 아래에서 ReduceLROnPlateau로 스케줄러를 바꾸면, LR이 천천히 내려가므로  
  200 epoch 안에 수렴하기 전에 한계에 부딪힐 수 있음.

### 변경 내용 & 해결 목적
| 파라미터 | 변경 전 | 변경 후 | 해결하려는 문제 |
|----------|---------|---------|----------------|
| `batch_size` | 32 | **16** | 에폭당 업데이트 2→5회로 증가, 그래디언트 노이즈 감소 |
| `epochs` | 200 | **300** | Plateau 스케줄러가 충분히 작동할 시간 확보 (Early Stopping이 실제 종료 결정) |
"""

BASE_DIR = Path('/content')          # 차트 저장 위치
CKPT_DIR = Path('/content/checkpoints')
CKPT_DIR.mkdir(exist_ok=True)

CFG = {
    "data": {
        # 업로드된 CSV 파일 경로
        "purchases_csv": str(DATA_DIR / "batch_purchases (1).csv"),
        "zone_kpi_csv":  str(DATA_DIR / "batch_zone_kpi (1).csv"),
        "window_size": 5,    # 입력 윈도우 크기 (며칠치 과거를 보는지)
        "horizon":     1,    # 예측 horizon (며칠 뒤를 예측하는지)
        "train_days":  84,   # 1~84일 → 학습
        "val_days":    20,   # 85~104일 → 검증 (Early Stopping 기준)
                             # 105일~ → 테스트 (최종 평가)
    },
    "model": {
        "d_model":  64,   # 임베딩 차원 (모든 레이어 공통)
        "n_heads":   4,   # Multi-head attention 헤드 수
        "n_layers":  2,   # TwoStageAttentionLayer 반복 횟수
        "n_router":  8,   # Cross-dimension router 토큰 수 (N²→N×8 복잡도 절감)
        "dropout":  0.2,  # Dropout 비율
    },
    "train": {
        "batch_size":     16,
        "lr":           0.0005,
        "weight_decay":  0.05,
        "epochs":        300,
        "patience":       30,    # Early Stopping 대기 에폭
        "grad_clip":      1.0,   # Gradient clipping 최댓값 (폭발 방지)
        "warmup_epochs":  5,     # LR Warmup 구간 (초반 불안정 학습 방지)
        "lambda_dwell":   0.5,   # 체류시간 손실 가중치
        "checkpoint_dir": str(CKPT_DIR),
    },
}

print("설정 로드 완료")

"""## 1. 데이터 로드 & EDA (탐색적 데이터 분석)

### 데이터 구조
| 파일 | 설명 | 주요 컬럼 |
|------|------|-----------|
| batch_purchases (1).csv | 구매 이벤트 raw (메인 학습 입력) | 일차, 시간대, 구역ID, 고객분류, 체류시간, 가격, 고객ID |
| batch_zone_kpi (1).csv | 구역 단위 집계 KPI (검증용) | 구역, 구매고객비중(%) |

### EDA에서 확인하는 항목
- 일별 구매 건수 추이 → train / val / test 분할 시각화
- 시간대별 구매 분포 → 피크 시간대 파악
- 구역별 구매 분포 → 주력 구역 파악
"""

df = pd.read_csv(CFG['data']['purchases_csv'])

# '시간대' 컬럼은 "9시", "10시" 형태 → 숫자만 추출해 hour 컬럼 생성
df['hour'] = df['시간대'].str.replace('시', '').astype(int)

print(f"총 행 수: {len(df):,}")
print(f"컬럼: {list(df.columns)}")
print()
print(f"구역     ({df['구역ID'].nunique():2d}개): {sorted(df['구역ID'].unique())}")
print(f"시간대   ({df['hour'].nunique():2d}개): {sorted(df['hour'].unique())}")
print(f"고객분류 ({df['고객분류'].nunique():2d}개): {sorted(df['고객분류'].unique())}")
print(f"일차 범위: {df['일차'].min()}~{df['일차'].max()}일 (총 {df['일차'].nunique()}일)")
df.head()

fig, axes = plt.subplots(1, 3, figsize=(15, 4))

# 차트 1: 일별 구매 건수 추이 (분할 기준선 포함)
daily = df.groupby('일차').size()
axes[0].plot(daily.index, daily.values, linewidth=1)
axes[0].axvline(84,  color='r',      linestyle='--', label='train/val split')
axes[0].axvline(104, color='orange', linestyle='--', label='val/test split')
axes[0].set_title('Daily Purchase Count')
axes[0].set_xlabel('Day')
axes[0].legend()

# 차트 2: 시간대별 구매 건수 (어느 시간대가 활발한지)
hourly = df.groupby('hour').size()
axes[1].bar(hourly.index, hourly.values)
axes[1].set_title('Purchase by Hour')
axes[1].set_xlabel('Hour')

# 차트 3: 구역별 구매 건수 (주력 구역 식별)
zone = df.groupby('구역명').size().sort_values(ascending=True)
axes[2].barh(zone.index, zone.values)
axes[2].set_title('Purchase by Zone')

plt.tight_layout()
plt.show()

"""## 2. Dataset — KPIGridDataset

### 전처리 파이프라인
```
batch_purchases CSV
        ↓
(일차, 구역ID, 시간대, 고객분류) 기준 groupby 집계
        ↓
3D grid [D, Z, T, C, F]   ← 고객군(C) 차원 추가 (원본 대비)
        ↓
정규화 (활성 셀 기준 mean/std, 수량형은 log1p 후 z-score)
        ↓
슬라이딩 윈도우 → (x [L, N, F], y_purchase [H, N], y_dwell [H, Z*T], dow [L])
```

### 입력 피처 4개 (F=4)
| idx | 피처 | 정규화 방식 |
|-----|------|-------------|
| 0 | 구매 이벤트 수 | log1p → z-score |
| 1 | 체류시간 평균 | z-score |
| 2 | 가격 평균 | z-score |
| 3 | 방문 고객 수 | log1p → z-score |

### 타겟 2종류
| 타겟 | shape | 설명 |
|------|-------|------|
| target_purchase | [H, Z\*T\*C] | log1p(구매수) — 336 토큰 전체 |
| target_dwell | [H, Z\*T] | 체류시간 — 고객군 차원 평균 |
"""

class KPIGridDataset(Dataset):
    """
    batch_purchases CSV를 3D grid로 변환하고 슬라이딩 윈도우 샘플을 반환한다.

    입력 형태: [window_size, Z*T*C, F]  (정규화된 피처)
    타겟 형태:
      purchase: [horizon, Z*T*C]  (log1p 구매수)
      dwell:    [horizon, Z*T]    (체류시간, 고객군 평균)
    """

    N_FEATURES = 4  # 구매수, 체류시간, 가격, 방문고객수

    def __init__(self, purchases_path, window_size=7, horizon=1,
                 day_range=None, stats=None):
        # ── 전체 CSV 로드 (카테고리 매핑은 항상 전체 기준) ──────
        df_all = pd.read_csv(purchases_path)
        df_all['hour'] = df_all['시간대'].str.replace('시', '').astype(int)

        # 카테고리를 전체 CSV 기준으로 정렬 → Train/Val/Test 간 인덱스 통일
        self.zones   = sorted(df_all['구역ID'].unique())
        self.hours   = sorted(df_all['hour'].unique())
        self.classes = sorted(df_all['고객분류'].unique())
        self.zone2idx = {z: i for i, z in enumerate(self.zones)}
        self.hour2idx = {h: i for i, h in enumerate(self.hours)}
        self.cls2idx  = {c: i for i, c in enumerate(self.classes)}
        self.n_zones   = len(self.zones)
        self.n_hours   = len(self.hours)
        self.n_classes = len(self.classes)
        self.n_tokens  = self.n_zones * self.n_hours * self.n_classes  # 336

        # ── day_range 필터 적용 ─────────────────────────────────
        df = (df_all if day_range is None
              else df_all[df_all['일차'].between(*day_range)])
        days_present = sorted(df['일차'].unique())
        n_days = len(days_present)
        self.day2seq = {d: i for i, d in enumerate(days_present)}
        self.seq2day = {i: d for d, i in self.day2seq.items()}

        # ── 3D grid 빌드 & 정규화 ──────────────────────────────
        self.grid_raw = self._build_grid(df, n_days)
        self.stats    = stats if stats is not None else self._fit_stats(self.grid_raw)
        self.grid     = self._normalize(self.grid_raw, self.stats)

        # ── 타겟 생성 ───────────────────────────────────────────
        # 타겟 1: 구매수 — long-tail 완화를 위해 log1p 변환
        self.target_purchase_raw = self.grid_raw[..., 0]                       # [D, Z, T, C]
        self.target_purchase     = np.log1p(self.target_purchase_raw).astype(np.float32)

        # 타겟 2: 체류시간 — 고객군(C) 차원 평균 → 구역×시간대 단위
        self.target_dwell_raw = self.grid_raw[..., 1].mean(axis=-1)            # [D, Z, T]
        self.target_dwell     = self.target_dwell_raw.astype(np.float32)

        # ── 슬라이딩 윈도우 인덱스 ─────────────────────────────
        self.window_size = window_size
        self.horizon     = horizon
        max_start        = n_days - window_size - horizon + 1
        self.indices     = list(range(max(0, max_start)))

    def _build_grid(self, df, n_days):
        """CSV를 (일차, 구역, 시간대, 고객분류) 기준으로 집계해 5D 배열로 변환한다."""
        Z, T, C, F = self.n_zones, self.n_hours, self.n_classes, self.N_FEATURES
        grid = np.zeros((n_days, Z, T, C, F), dtype=np.float32)

        for (day, zone, hour, cls), grp in df.groupby(['일차', '구역ID', 'hour', '고객분류']):
            if day not in self.day2seq:
                continue
            d, zi, ti = self.day2seq[day], self.zone2idx[zone], self.hour2idx[hour]
            ci = self.cls2idx.get(cls)
            if ci is None:
                continue

            grid[d, zi, ti, ci, 0] = len(grp)                  # 구매 수
            grid[d, zi, ti, ci, 1] = grp['체류시간'].mean()     # 평균 체류시간
            grid[d, zi, ti, ci, 2] = grp['가격'].mean()         # 평균 가격
            grid[d, zi, ti, ci, 3] = grp['에이전트ID'].nunique()    # 방문 고객 수

        return grid

    @staticmethod
    def _fit_stats(grid):
        """Train grid에서 정규화 통계(mean, std)를 계산한다. 활성 셀만 사용."""
        F    = grid.shape[-1]
        flat = grid.reshape(-1, F)
        nz   = flat[flat[:, 0] > 0]   # 구매 있는 셀만 (0 셀이 통계를 왜곡하지 않도록)
        log_idx = {0, 3}              # 카운트형 피처: log1p 후 정규화
        means, stds = np.zeros(F, np.float32), np.ones(F, np.float32)

        for i in range(F):
            col = nz[:, i] if len(nz) else flat[:, i]
            if i in log_idx:
                col = np.log1p(col)
            means[i] = col.mean() if len(col) else 0.0
            stds[i]  = col.std()  + 1e-6

        return {'means': means, 'stds': stds, 'log_idx': list(log_idx)}

    @staticmethod
    def _normalize(grid, stats):
        """fit_stats 통계로 z-score 정규화한다. log_idx 피처는 log1p 먼저 적용."""
        out, log_idx = grid.copy(), set(stats['log_idx'])
        for i in range(grid.shape[-1]):
            if i in log_idx:
                out[..., i] = np.log1p(out[..., i])
            out[..., i] = (out[..., i] - stats['means'][i]) / stats['stds'][i]
        return out.astype(np.float32)

    def __len__(self):
        return len(self.indices)

    def __getitem__(self, idx):
        """슬라이딩 윈도우 샘플을 반환한다. (x, y_purchase, y_dwell, dow)"""
        s   = self.indices[idx]
        x   = self.grid[s: s + self.window_size]                              # [L, Z, T, C, F]
        yp  = self.target_purchase[s+self.window_size: s+self.window_size+self.horizon]  # [H, Z, T, C]
        yd  = self.target_dwell[s+self.window_size: s+self.window_size+self.horizon]     # [H, Z, T]
        days = [self.seq2day[s + i] for i in range(self.window_size)]
        dow  = np.array([(d - 1) % 7 for d in days], dtype=np.int64)         # [L]

        L, Z, T, C, F = x.shape
        return (torch.from_numpy(x.reshape(L, Z*T*C, F)),
                torch.from_numpy(yp.reshape(self.horizon, Z*T*C)),
                torch.from_numpy(yd.reshape(self.horizon, Z*T)),
                torch.from_numpy(dow))

# 데이터셋 생성 및 shape 확인
dc = CFG['data']
W, H      = dc['window_size'], dc['horizon']
train_end = dc['train_days']
val_end   = train_end + dc['val_days']

# Train: 정규화 통계를 이 데이터에서 fit
train_ds = KPIGridDataset(dc['purchases_csv'], W, H, day_range=(1, train_end))
# Val: Train stats를 그대로 주입 (데이터 누수 방지)
val_ds   = KPIGridDataset(dc['purchases_csv'], W, H,
                           day_range=(train_end + 1, val_end), stats=train_ds.stats)

print(f"구역: {train_ds.n_zones}개  시간대: {train_ds.n_hours}개  "
      f"고객군: {train_ds.n_classes}개  토큰: {train_ds.n_tokens}개")
print(f"Train: {len(train_ds)}샘플  Val: {len(val_ds)}샘플")

x0, yp0, yd0, dow0 = train_ds[0]
print(f"\n입력  shape : {x0.shape}   (L={W}, N={train_ds.n_tokens}, F={KPIGridDataset.N_FEATURES})")
print(f"구매  target : {yp0.shape}   체류 target : {yd0.shape}")
print(f"DoW   shape  : {dow0.shape}")

"""## 3. 모델 아키텍처 — KPICrossformer

```
입력: [B, L=7, N=336, F=4]

임베딩 (d=96):
  input_proj  [F→d]     ─── 피처 → d차원
  zone_emb [Z, d] ──┐
  hour_emb [T, d] ──┤→ 토큰별 구조 정보
  cls_emb  [C, d] ──┘
  pos_emb  [L, d]   ─── 날짜 위치
  dow_emb  [7, d]   ─── 요일

TwoStageAttentionLayer × 3:
  Stage 1: Cross-time  [B*N, L, d]
    → 각 토큰이 7일 시점에 걸쳐 attend ("이 구역의 7일 패턴은?")
  Stage 2: Cross-dimension  [B*L, N, d]  (Router 기반)
    gather:    router(8개) ← N 토큰  (N→8 집약)
    broadcast: N 토큰 ← router       (8→N 전파)
    → N²를 N×8로 복잡도 절감

예측 헤드 (마지막 타임스텝):
  purchase_head → [B, H, N=336]   log1p(구매수)
  dwell_head    → [B, H, Z*T=84]  체류시간 (C 차원 평균 후)
```

> **왜 SmoothL1?** 구매수는 0이 많고 outlier가 존재 → MSE 대신 이상치 강건한 SmoothL1  
> **왜 log1p 타겟?** right-skewed 분포 완화 → 모델이 더 고르게 학습
"""

class TwoStageAttentionLayer(nn.Module):
    """
    Crossformer 핵심 블록.
    Stage 1: Cross-time  — 각 토큰이 L 시점에 걸쳐 self-attention
    Stage 2: Cross-dim   — n_router 가상 토큰을 중계자로 N 토큰 간 정보 교환
    """

    def __init__(self, d_model, n_heads, n_router, dropout=0.1):
        super().__init__()

        # Stage 1: Cross-time attention
        self.time_attn = nn.MultiheadAttention(d_model, n_heads, dropout=dropout, batch_first=True)
        self.norm_t    = nn.LayerNorm(d_model)

        # Stage 2: Cross-dimension attention (Router 기반)
        # router: 학습 가능한 n_router개 가상 토큰 — N 토큰 정보를 요약하는 중계 허브
        self.router      = nn.Parameter(torch.randn(1, n_router, d_model))
        self.gather_attn = nn.MultiheadAttention(d_model, n_heads, dropout=dropout, batch_first=True)  # router ← N
        self.broad_attn  = nn.MultiheadAttention(d_model, n_heads, dropout=dropout, batch_first=True)  # N ← router
        self.norm_r      = nn.LayerNorm(d_model)
        self.norm_d      = nn.LayerNorm(d_model)

        # FFN: d → 4d → d (비선형 표현력 강화)
        self.ffn = nn.Sequential(
            nn.Linear(d_model, d_model * 4),
            nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(d_model * 4, d_model),
        )
        self.norm_f = nn.LayerNorm(d_model)
        self.drop   = nn.Dropout(dropout)

    def forward(self, x):
        # x: [B, L, N, d]
        B, L, N, d = x.shape

        # Stage 1: Cross-time ─────────────────────────────────
        # [B, L, N, d] → [B*N, L, d]: 토큰을 배치 차원으로 합쳐 시점 attention
        xt     = x.permute(0, 2, 1, 3).reshape(B * N, L, d)
        xt2, _ = self.time_attn(xt, xt, xt)
        xt     = self.norm_t(xt + self.drop(xt2))
        x      = xt.reshape(B, N, L, d).permute(0, 2, 1, 3)   # 복원

        # Stage 2: Cross-dimension via Router ─────────────────
        xd    = x.reshape(B * L, N, d)                          # 시점별 독립 처리
        r     = self.router.expand(B * L, -1, -1)               # [B*L, n_router, d]
        r2, _ = self.gather_attn(r, xd, xd)                     # gather: router ← N 토큰
        r     = self.norm_r(r + self.drop(r2))
        xd2, _ = self.broad_attn(xd, r, r)                      # broadcast: N 토큰 ← router
        xd    = self.norm_d(xd + self.drop(xd2))
        x     = xd.reshape(B, L, N, d)

        # FFN
        x = self.norm_f(x + self.drop(self.ffn(x)))
        return x


class KPICrossformer(nn.Module):
    """
    구역 × 시간대 × 고객군 3D grid 시계열 → KPI 예측

    입력:  x [B, L, N, F]  (N = Z*T*C = 336),  dow [B, L]
    출력:  purchase [B, H, N],  dwell [B, H, Z*T]
    """

    def __init__(self, n_zones, n_hours, n_classes, n_features,
                 d_model=96, n_heads=4, n_layers=3, n_router=8,
                 dropout=0.1, horizon=1, max_window=64):
        super().__init__()
        self.n_zones, self.n_hours, self.n_classes = n_zones, n_hours, n_classes
        self.n_tokens = n_zones * n_hours * n_classes   # 336

        # 피처 투영: F=4 → d_model
        self.input_proj = nn.Linear(n_features, d_model)

        # 분리 임베딩: 구역 + 시간대 + 고객군 (각각 독립 임베딩 후 합산)
        self.zone_emb = nn.Embedding(n_zones,   d_model)
        self.hour_emb = nn.Embedding(n_hours,   d_model)
        self.cls_emb  = nn.Embedding(n_classes, d_model)
        self.pos_emb  = nn.Embedding(max_window, d_model)  # 날짜 위치
        self.dow_emb  = nn.Embedding(7,          d_model)  # 요일

        # Crossformer 블록 스택
        self.blocks = nn.ModuleList([
            TwoStageAttentionLayer(d_model, n_heads, n_router, dropout)
            for _ in range(n_layers)
        ])

        # 헤드 1: 구매수 (N=336 토큰 전체)
        self.purchase_head = nn.Sequential(nn.LayerNorm(d_model), nn.Linear(d_model, horizon))
        # 헤드 2: 체류시간 (고객군 차원 평균 후 Z*T 토큰)
        self.dwell_head    = nn.Sequential(nn.LayerNorm(d_model), nn.Linear(d_model, horizon))

    def forward(self, x, dow):
        B, L, N, _ = x.shape
        Z, T, C    = self.n_zones, self.n_hours, self.n_classes

        # 1. 피처 투영
        h = self.input_proj(x)   # [B, L, N, d]

        # 2. 토큰 임베딩: 구역·시간대·고객군 구조 정보 부여
        zone_ids  = torch.arange(Z, device=x.device).repeat_interleave(T * C)
        hour_ids  = torch.arange(T, device=x.device).repeat(Z).repeat_interleave(C)
        cls_ids   = torch.arange(C, device=x.device).repeat(Z * T)
        token_emb = self.zone_emb(zone_ids) + self.hour_emb(hour_ids) + self.cls_emb(cls_ids)
        h = h + token_emb.view(1, 1, N, -1)

        # 3. 위치·요일 임베딩
        h = h + self.pos_emb(torch.arange(L, device=x.device).view(1, L, 1))
        h = h + self.dow_emb(dow).unsqueeze(2)   # [B, L, 1, d] broadcast

        # 4. Crossformer 블록 통과
        for block in self.blocks:
            h = block(h)

        # 5. 마지막 타임스텝으로 예측
        last     = h[:, -1, :, :]   # [B, N, d]
        purchase = self.purchase_head(last).permute(0, 2, 1)   # [B, H, N]

        # 체류시간: C 차원 평균 → Z*T 단위
        last_zt = last.reshape(B, Z, T, C, -1).mean(dim=3).reshape(B, Z*T, -1)
        dwell   = self.dwell_head(last_zt).permute(0, 2, 1)    # [B, H, Z*T]

        return purchase, dwell

# 모델 생성 및 파라미터 수 확인
mc = CFG['model']
model = KPICrossformer(
    n_zones    = train_ds.n_zones,
    n_hours    = train_ds.n_hours,
    n_classes  = train_ds.n_classes,
    n_features = KPIGridDataset.N_FEATURES,
    d_model    = mc['d_model'],
    n_heads    = mc['n_heads'],
    n_layers   = mc['n_layers'],
    n_router   = mc['n_router'],
    dropout    = mc['dropout'],
    horizon    = H,
    max_window = max(W, 64),
).to(device)

total_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"모델 파라미터 수: {total_params:,}")
print(model)

"""## 4. 학습

### 학습 설정 요약
| 항목 | 값 |
|------|----|
| Optimizer | AdamW (lr=0.0005, weight_decay=0.05) |
| Loss | SmoothL1 (β=0.5) + λ×dwell_loss |
| LR Schedule | Warmup 5 epoch → ReduceLROnPlateau |
| Early Stopping | patience=20 |
| 타겟 공간 | log1p(구매수) + 체류시간 |

## 🔧 수정사항 — LR 스케줄러: Cosine Decay → ReduceLROnPlateau

### 기존 문제
기존 **Cosine Decay**는 val loss와 무관하게 epoch이 지날수록 LR을 무조건 감소시킴.

```
epoch 40:  val=0.4569,  lr=0.00046  ← 아직 개선 중
epoch 108: val=0.4528,  lr=0.00024  ← LR이 절반 이하, val은 0.004만 줄었는데 학습 종료
```

→ val이 아직 개선되고 있는데 LR이 먼저 바닥나서 Early Stopping이 트리거됨.

### 변경 내용 & 해결 목적
**ReduceLROnPlateau**: val loss가 `patience=10` epoch 동안 개선 없을 때만 LR을 절반으로 줄임.

| 항목 | Cosine Decay (변경 전) | ReduceLROnPlateau (변경 후) |
|------|-----------------------|---------------------------|
| LR 감소 조건 | 시간 경과 무조건 감소 | val loss 정체 시에만 감소 |
| 개선 중인 구간 | LR이 줄어 학습 방해 | LR 유지 → 계속 학습 가능 |
| 수렴 후 | LR이 이미 바닥 | 정체 감지 후 LR 절반으로 → 세밀 탐색 |

Warmup 5 epoch은 기존과 동일하게 유지하고, 그 이후부터 Plateau 스케줄러가 작동함.

## 🔧 수정사항 — Val EMA 스무딩 + patience 복원

### 기존 문제
Val 샘플이 15개뿐이라 샘플 1개의 예측 오차가 val loss 전체의 **6.7%** 를 차지함.  
그 결과 val loss가 매 epoch마다 크게 진동해 잘못된 판단을 유발함.

```
Epoch 28: val=0.4560  *   ← best 갱신
Epoch 35: val=0.4637      ← 0.008 급등 (샘플 1~2개가 틀린 것)
Epoch 38: val=0.4557  *   ← 다시 best
Epoch 40: val=0.4634      ← 또 0.008 급등
```

**Raw val로 판단했을 때 발생한 두 가지 부작용:**
1. **ReduceLROnPlateau** 가 진짜 정체가 아닌 노이즈 스파이크에 반응해 LR을 조기 감소
2. **Early Stopping** 이 실제 개선 추세인데도 스파이크를 보고 patience를 소진

### 변경 내용 & 해결 목적

**Val EMA (지수이동평균)** 로 val loss를 평활화한 뒤, 이 값으로 Early Stopping과 ReduceLROnPlateau를 판단.

```
ema_val = 0.7 × (이전 EMA) + 0.3 × (현재 val)
```

| 항목 | 변경 전 | 변경 후 | 해결하는 문제 |
|------|---------|---------|--------------|
| Early Stopping 기준 | raw val (노이즈 큼) | **EMA val** (평활화) | 노이즈 스파이크로 인한 조기 종료 방지 |
| Plateau 감지 기준 | raw val | **EMA val** | 가짜 정체 신호로 LR 조기 감소 방지 |
| patience | 20 | **30** | EMA도 천천히 반응하므로 여유 부여 |
| 학습 곡선 출력 | Train / Val | Train / Val(raw) / **Val(EMA)** | 평활화 효과 시각적으로 확인 가능 |
"""

def set_seed(seed=42):
    """재현성을 위해 모든 난수 시드를 고정한다."""
    random.seed(seed); np.random.seed(seed)
    torch.manual_seed(seed); torch.cuda.manual_seed_all(seed)

set_seed(42)
tc = CFG['train']

train_loader = DataLoader(train_ds, batch_size=tc['batch_size'], shuffle=True)
val_loader   = DataLoader(val_ds,   batch_size=tc['batch_size'])

optimizer = torch.optim.AdamW(model.parameters(), lr=tc['lr'], weight_decay=tc['weight_decay'])
criterion = nn.SmoothL1Loss(beta=0.5)
lam       = tc['lambda_dwell']

epochs, warmup = tc['epochs'], tc['warmup_epochs']

def lr_warmup(epoch):
    return (epoch + 1) / warmup if epoch < warmup else 1.0

warmup_scheduler  = torch.optim.lr_scheduler.LambdaLR(optimizer, lr_warmup)
plateau_scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer, mode='min', factor=0.5, patience=10, min_lr=1e-6
)

ckpt_path  = Path(tc['checkpoint_dir']) / 'best_kpi.pt'
best_ema   = float('inf')   # EMA 기준 best (Early Stopping 판단에 사용)
best_val   = float('inf')   # raw val best (체크포인트 저장 기준)
no_improve = 0
ema_val    = None           # Val loss EMA (지수이동평균)
EMA_ALPHA  = 0.3            # 최신 값 반영 비율 (낮을수록 더 많이 평활화)
train_losses, val_losses, ema_losses = [], [], []

print(f"학습 시작  |  Device: {device}")
print(f"zones={train_ds.n_zones}  hours={train_ds.n_hours}  classes={train_ds.n_classes}  tokens={train_ds.n_tokens}")
print(f"Train={len(train_ds)}샘플  Val={len(val_ds)}샘플\n")

for epoch in range(1, epochs + 1):

    # ── Train ───────────────────────────────────────────────
    model.train()
    train_loss = 0.0
    for x, yp, yd, dow in train_loader:
        x, yp, yd, dow = x.to(device), yp.to(device), yd.to(device), dow.to(device)
        pred_p, pred_d = model(x, dow)
        loss = criterion(pred_p, yp) + lam * criterion(pred_d, yd)
        optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), tc['grad_clip'])
        optimizer.step()
        train_loss += loss.item() * x.size(0)
    train_loss /= len(train_ds)

    # ── Validation ──────────────────────────────────────────
    model.eval()
    val_loss = 0.0
    with torch.no_grad():
        for x, yp, yd, dow in val_loader:
            x, yp, yd, dow = x.to(device), yp.to(device), yd.to(device), dow.to(device)
            pred_p, pred_d = model(x, dow)
            val_loss += (criterion(pred_p, yp) + lam * criterion(pred_d, yd)).item() * x.size(0)
    val_loss /= max(len(val_ds), 1)

    # ── Val EMA 계산 (노이즈 평활화) ────────────────────────
    # 첫 epoch은 raw val 그대로, 이후는 지수이동평균으로 갱신
    ema_val = val_loss if ema_val is None else (1 - EMA_ALPHA) * ema_val + EMA_ALPHA * val_loss

    # ── LR 스케줄 업데이트 ──────────────────────────────────
    if epoch <= warmup:
        warmup_scheduler.step()
    else:
        plateau_scheduler.step(ema_val)   # Plateau 판단도 EMA 기준

    current_lr = optimizer.param_groups[0]['lr']
    train_losses.append(train_loss)
    val_losses.append(val_loss)
    ema_losses.append(ema_val)

    # ── Early Stopping: EMA val 기준으로 판단 ───────────────
    improved = ema_val < best_ema - 1e-5
    if epoch % 5 == 0 or improved:
        print(f"Epoch {epoch:3d} | lr={current_lr:.5f} | "
              f"train={train_loss:.4f} | val={val_loss:.4f} | ema={ema_val:.4f}"
              f"{'  *' if improved else ''}")

    if improved:
        best_ema = ema_val
        # 체크포인트는 raw val 기준 최저점 저장
        if val_loss < best_val:
            best_val = val_loss
        no_improve = 0
        torch.save({
            'epoch': epoch, 'model': model.state_dict(), 'val_loss': float(val_loss),
            'cfg_model': mc, 'cfg_data': dc, 'stats': train_ds.stats,
            'zone2idx': train_ds.zone2idx, 'hour2idx': train_ds.hour2idx,
            'cls2idx': train_ds.cls2idx,
            'n_zones': train_ds.n_zones, 'n_hours': train_ds.n_hours, 'n_classes': train_ds.n_classes,
        }, ckpt_path)
    else:
        no_improve += 1
        if no_improve >= tc['patience']:
            print(f"\nEarly stopping @ epoch {epoch} (patience={tc['patience']} 소진)")
            break

print(f"\nBest val loss: {best_val:.4f}  →  {ckpt_path}")

plt.figure(figsize=(8, 4))
plt.plot(train_losses, label='Train Loss')
plt.plot(val_losses,   label='Val Loss (raw)', alpha=0.4)
plt.plot(ema_losses,   label='Val Loss (EMA)', linewidth=2)
plt.xlabel('Epoch'); plt.ylabel('SmoothL1 Loss')
plt.title('Training Curve'); plt.legend()
plt.tight_layout(); plt.show()

"""## 5. 평가 — KPI #2, #3, #5, #7, #8

### KPI 계산 방식
| KPI | 계산 방식 |
|-----|-----------|
| #2 전체 구매전환율 | 전체 토큰 구매수 합산 (proxy) |
| #3 구역별 체류시간 | dwell_head 예측값, 시간대 평균 |
| #5 고객군별 구매수 | C 차원 합산 |
| #7 체류 대비 전환 효율 | zone_buy / zone_dwell |
| #8 비효율 구역 지수 | minmax(체류) × (1 − minmax(전환)) |
"""

def compute_kpis(preds_p, trues_p, preds_d, trues_d, n_zones, n_hours, n_classes):
    """예측값에서 KPI #2, #3, #5, #7, #8을 계산한다."""
    Z, T, C = n_zones, n_hours, n_classes

    # log1p 역변환 → 원래 구매수 공간 복원
    p_buy = np.expm1(preds_p).clip(0)
    t_buy = np.expm1(trues_p)

    p4  = p_buy.reshape(-1, Z, T, C)   # [S*H, Z, T, C]
    t4  = t_buy.reshape(-1, Z, T, C)
    pd3 = preds_d.reshape(-1, Z, T)    # [S*H, Z, T]
    td3 = trues_d.reshape(-1, Z, T)

    def mape(p, t):
        mask = t > 0
        return float(np.mean(np.abs(p[mask] - t[mask]) / t[mask].clip(1e-6)) * 100) if mask.any() else float('nan')

    def minmax_norm(arr):
        return (arr - arr.min()) / (arr.max() - arr.min() + 1e-6)

    # KPI #2: 전체 구매수 총합 (proxy)
    total_p, total_t = p4.sum(axis=(1,2,3)), t4.sum(axis=(1,2,3))

    # KPI #3: 구역별 체류시간 (시간대 평균)
    zone_dwell_p, zone_dwell_t = pd3.mean(axis=2), td3.mean(axis=2)  # [S*H, Z]

    # KPI #5: 고객군별 구매수 (구역·시간대 합산)
    cls_p, cls_t = p4.sum(axis=(1,2)), t4.sum(axis=(1,2))             # [S*H, C]

    # KPI #7, #8 기반: 구역별 구매수
    zone_buy_p, zone_buy_t = p4.sum(axis=(2,3)), t4.sum(axis=(2,3))   # [S*H, Z]

    # KPI #7: 체류 대비 전환 효율 = 구매수 / 체류시간
    eff_p = zone_buy_p.mean(0) / (zone_dwell_p.mean(0) + 1e-6)
    eff_t = zone_buy_t.mean(0) / (zone_dwell_t.mean(0) + 1e-6)

    # KPI #8: 비효율 구역 지수 = norm(체류) × (1 - norm(전환))
    ineff_p = minmax_norm(zone_dwell_p.mean(0)) * (1 - minmax_norm(zone_buy_p.mean(0)))
    ineff_t = minmax_norm(zone_dwell_t.mean(0)) * (1 - minmax_norm(zone_buy_t.mean(0)))

    return {
        'kpi2_overall':     {'pred_mean': float(total_p.mean()), 'true_mean': float(total_t.mean()),
                             'mae': float(np.abs(total_p-total_t).mean()), 'mape': mape(total_p, total_t)},
        'kpi3_zone_dwell':  {'pred': zone_dwell_p.mean(0), 'true': zone_dwell_t.mean(0),
                             'mae': float(np.abs(zone_dwell_p-zone_dwell_t).mean()),
                             'mape': float((np.abs(zone_dwell_p-zone_dwell_t)/(zone_dwell_t+1e-6)).mean()*100),
                             'spearman': float(spearmanr(zone_dwell_p.mean(0), zone_dwell_t.mean(0)).statistic)},
        'kpi5_class':       {'pred': cls_p.mean(0), 'true': cls_t.mean(0),
                             'mape': float((np.abs(cls_p-cls_t)/(cls_t+1e-6)).mean()*100),
                             'spearman': float(spearmanr(cls_p.mean(0), cls_t.mean(0)).statistic)},
        'kpi7_efficiency':  {'pred': eff_p, 'true': eff_t,
                             'mape': float((np.abs(eff_p-eff_t)/(eff_t+1e-6)).mean()*100),
                             'spearman': float(spearmanr(eff_p, eff_t).statistic)},
        'kpi8_inefficiency':{'pred': ineff_p, 'true': ineff_t,
                             'spearman': float(spearmanr(ineff_p, ineff_t).statistic)},
    }

# 체크포인트 로드 & Test 데이터셋 생성
ckpt     = torch.load(ckpt_path, map_location=device, weights_only=False)
dc_ckpt  = ckpt['cfg_data']
mc_ckpt  = ckpt['cfg_model']

test_start = dc_ckpt['train_days'] + dc_ckpt['val_days'] + 1
test_ds    = KPIGridDataset(dc_ckpt['purchases_csv'], W, H,
                             day_range=(test_start, 9999), stats=ckpt['stats'])
test_loader = DataLoader(test_ds, batch_size=64)

# 모델 복원
model_eval = KPICrossformer(
    n_zones=ckpt['n_zones'], n_hours=ckpt['n_hours'], n_classes=ckpt['n_classes'],
    n_features=KPIGridDataset.N_FEATURES,
    d_model=mc_ckpt['d_model'], n_heads=mc_ckpt['n_heads'],
    n_layers=mc_ckpt['n_layers'], n_router=mc_ckpt['n_router'],
    dropout=mc_ckpt['dropout'], horizon=H, max_window=max(W, 64),
).to(device)
model_eval.load_state_dict(ckpt['model'])
model_eval.eval()   # Dropout 비활성화

# 추론
preds_p, trues_p, preds_d, trues_d = [], [], [], []
with torch.no_grad():
    for x, yp, yd, dow in test_loader:
        pp, pd = model_eval(x.to(device), dow.to(device))
        preds_p.append(pp.cpu().numpy()); trues_p.append(yp.numpy())
        preds_d.append(pd.cpu().numpy()); trues_d.append(yd.numpy())

preds_p = np.concatenate(preds_p); trues_p = np.concatenate(trues_p)
preds_d = np.concatenate(preds_d); trues_d = np.concatenate(trues_d)

# KPI 계산 & 출력
kpis = compute_kpis(preds_p, trues_p, preds_d, trues_d,
                    ckpt['n_zones'], ckpt['n_hours'], ckpt['n_classes'])

print("=" * 60)
print("평가 결과 (Test set)")
print("=" * 60)
k2=kpis['kpi2_overall']
print(f"\n[KPI #2] 전체 구매전환율   예측={k2['pred_mean']:.1f}  실제={k2['true_mean']:.1f}  MAE={k2['mae']:.2f}  MAPE={k2['mape']:.1f}%")
k3=kpis['kpi3_zone_dwell']
print(f"[KPI #3] 구역별 체류시간    MAE={k3['mae']:.2f}초  MAPE={k3['mape']:.1f}%  ρ={k3['spearman']:.3f}")
k5=kpis['kpi5_class']
print(f"[KPI #5] 고객군별 구매수    MAPE={k5['mape']:.1f}%  ρ={k5['spearman']:.3f}")
k7=kpis['kpi7_efficiency']
print(f"[KPI #7] 체류 대비 전환효율  MAPE={k7['mape']:.1f}%  ρ={k7['spearman']:.3f}")
k8=kpis['kpi8_inefficiency']
print(f"[KPI #8] 비효율 구역 지수   ρ={k8['spearman']:.3f}")

"""## 6. 결과 시각화

| 위치 | 내용 |
|------|------|
| [0,0] | KPI #3: 구역별 체류시간 예측 vs 실제 |
| [0,1] | KPI #5: 고객군별 구매수 예측 vs 실제 |
| [1,0] | KPI #7: 체류 대비 전환 효율 |
| [1,1] | KPI #8: 비효율 구역 지수 (빨강=개선 필요) |
"""

idx2zone   = {v: k for k, v in ckpt['zone2idx'].items()}
idx2cls    = {v: k for k, v in ckpt['cls2idx'].items()}
zone_names = [idx2zone[i] for i in range(ckpt['n_zones'])]
cls_names  = [idx2cls[i]  for i in range(ckpt['n_classes'])]
Z, C       = ckpt['n_zones'], ckpt['n_classes']
x_pos, w   = np.arange(Z), 0.35

fig, axes = plt.subplots(2, 3, figsize=(18, 10))

# [0,0] KPI #2: Overall Purchase Conversion (proxy)
k2 = kpis['kpi2_overall']
axes[0,0].bar(['Predicted', 'Actual'], [k2['pred_mean'], k2['true_mean']],
               color=['steelblue', 'orange'], alpha=0.85)
axes[0,0].set_title(f"KPI #2 Overall Purchase Count\nMAE={k2['mae']:.1f}  MAPE={k2['mape']:.1f}%")
axes[0,0].set_ylabel('Total Purchase Count (avg per day)')

# [0,1] KPI #3: Avg Dwell Time by Zone
k3 = kpis['kpi3_zone_dwell']
axes[0,1].bar(x_pos-w/2, k3['pred'], w, label='Predicted', alpha=0.8)
axes[0,1].bar(x_pos+w/2, k3['true'], w, label='Actual',    alpha=0.8)
axes[0,1].set_xticks(x_pos); axes[0,1].set_xticklabels(zone_names, rotation=30, ha='right')
axes[0,1].set_title(f"KPI #3 Avg Dwell Time by Zone\nMAPE={k3['mape']:.1f}%  \u03c1={k3['spearman']:.3f}")
axes[0,1].set_ylabel('Dwell Time (sec)'); axes[0,1].legend()

# [0,2] KPI #5: Purchase Count by Customer Class
k5 = kpis['kpi5_class']
x_cls = np.arange(C)
axes[0,2].bar(x_cls-w/2, k5['pred'], w, label='Predicted', alpha=0.8)
axes[0,2].bar(x_cls+w/2, k5['true'], w, label='Actual',    alpha=0.8)
axes[0,2].set_xticks(x_cls); axes[0,2].set_xticklabels(cls_names, rotation=20, ha='right')
axes[0,2].set_title(f"KPI #5 Purchase Count by Customer Class\nMAPE={k5['mape']:.1f}%  \u03c1={k5['spearman']:.3f}")
axes[0,2].set_ylabel('Avg Purchase Count'); axes[0,2].legend()

# [1,0] KPI #7: Conversion Efficiency vs Dwell
k7 = kpis['kpi7_efficiency']
axes[1,0].barh(zone_names, k7['pred'], alpha=0.8, label='Predicted')
axes[1,0].barh(zone_names, k7['true'], alpha=0.5, label='Actual')
axes[1,0].set_title(f"KPI #7 Conversion Efficiency vs Dwell\nMAPE={k7['mape']:.1f}%  \u03c1={k7['spearman']:.3f}")
axes[1,0].set_xlabel('Efficiency Index'); axes[1,0].legend()

# [1,1] KPI #8: Zone Inefficiency Index
k8 = kpis['kpi8_inefficiency']
cp = ['tomato' if v>0.5 else 'steelblue' for v in k8['pred']]
ct = ['tomato' if v>0.5 else 'steelblue' for v in k8['true']]
axes[1,1].bar(x_pos-w/2, k8['pred'], w, color=cp, alpha=0.8, label='Predicted')
axes[1,1].bar(x_pos+w/2, k8['true'], w, color=ct, alpha=0.5, label='Actual')
axes[1,1].axhline(0.5, color='gray', linestyle='--', linewidth=0.8, label='threshold 0.5')
axes[1,1].set_xticks(x_pos); axes[1,1].set_xticklabels(zone_names, rotation=30, ha='right')
axes[1,1].set_title(f"KPI #8 Zone Inefficiency Index\n\u03c1={k8['spearman']:.3f}  red=needs improvement")
axes[1,1].legend()

# [1,2] 미사용 칸 숨김
axes[1,2].set_visible(False)

plt.tight_layout(); plt.show()

# 비효율 구역 TOP3 출력
top3 = sorted(zip(zone_names, k8['pred']), key=lambda x: x[1], reverse=True)[:3]
print("\n[Inefficiency Improvement Priority TOP3]")
print("  → Review: display layout / POP signage / price readability / bestseller placement")
for rank, (zone, score) in enumerate(top3, 1):
    print(f"  #{rank} {zone}: inefficiency index = {score:.3f}")

# (선택) Drive에 체크포인트 저장 — 런타임 종료 후에도 모델을 보존하려면 실행
# import shutil
# drive_save_path = '/content/drive/MyDrive/캡스톤/model/checkpoints/best_kpi.pt'
# shutil.copy(str(ckpt_path), drive_save_path)
# print(f"Drive 저장 완료: {drive_save_path}")

