# -*- coding: utf-8 -*-
"""RNN(LSTM)_times.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WIcZMFHzQ-FxL_4qjAyVIqMkv9w9-3hc
"""

# =========================================================
# 0. Import & Config
# =========================================================

import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

from sklearn.metrics import mean_absolute_error, mean_squared_error

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("device:", device)

def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

set_seed(42)

PURCHASE_CSV = "batch_purchases.csv"

CFG = {
    "window_size": 7,
    "horizon": 1,
    "train_days": 84,
    "val_days": 20,

    "batch_size": 32,
    "epochs": 200,
    "lr": 0.001,
    "weight_decay": 0.01,
    "patience": 30,

    "hidden_size": 128,
    "num_layers": 2,
    "dropout": 0.2,
}

"""# 1. Dataset 구성

1번 코드는 구매 데이터를 모델 학습에 사용할 수 있는 시계열 데이터셋 형태로 변환하는 과정이다. 원본 구매 데이터에서 시간대 정보를 숫자형으로 변환하고, 구역ID와 시간대를 기준으로 구역 × 시간대 단위의 grid를 생성하였다. 각 grid에는 구매건수, 구매고객수, 평균 체류시간, 평균 가격, 고객분류 비중, 구매비중, 전일 동일 구역·시간대 구매건수, 요일 정보가 feature로 포함된다. 타겟값은 다음 날의 구역·시간대별 구매비중으로 정의하였으며, 이는 실제 방문 고객 수가 없는 상황에서 구매전환율을 대체하기 위한 Proxy KPI로 사용하였다. 또한 train 데이터 기준으로 평균과 표준편차를 계산하여 정규화를 수행하고, validation/test 데이터에는 동일한 통계값을 적용하여 데이터 누수를 방지하였다.
"""

# =========================================================
# 1. Dataset
# KPI: 구역×시간대 구매전환율 Proxy
# 정의: 해당 구역×시간대 구매건수 / 해당 일자 전체 구매건수
# =========================================================

class ZoneHourConversionDataset(Dataset):
    """
    Transformer와 유사하게 구역×시간대 grid 유지.

    입력:
        x: [window_size, Z*T, F]

    타겟:
        y: [Z*T]
        다음 날 구역×시간대 구매비중 Proxy

    feature:
        0 구매건수
        1 구매고객수
        2 평균체류시간
        3 평균가격
        4 고객군_0 비중
        5 고객군_1 비중
        6 고객군_2 비중
        7 고객군_3 비중
        8 구역×시간대 구매비중
        9 전날 동일 구역×시간대 구매건수
        10 요일
    """

    BASE_FEATURES = 7
    EXTRA_FEATURES = 4
    N_FEATURES = 11

    def __init__(self, purchases_path, window_size=7, horizon=1,
                 day_range=None, stats=None,
                 zone2idx=None, hour2idx=None, class2idx=None):

        df_all = pd.read_csv(purchases_path)
        df_all["hour"] = df_all["시간대"].str.replace("시", "").astype(int)

        # 전체 CSV 기준 mapping 고정
        if zone2idx is None:
            zones = sorted(df_all["구역ID"].unique())
            self.zone2idx = {z: i for i, z in enumerate(zones)}
        else:
            self.zone2idx = zone2idx

        if hour2idx is None:
            hours = sorted(df_all["hour"].unique())
            self.hour2idx = {h: i for i, h in enumerate(hours)}
        else:
            self.hour2idx = hour2idx

        if class2idx is None:
            classes = sorted(df_all["고객분류"].unique())
            self.class2idx = {c: i for i, c in enumerate(classes)}
        else:
            self.class2idx = class2idx

        self.idx2zone = {v: k for k, v in self.zone2idx.items()}
        self.idx2hour = {v: k for k, v in self.hour2idx.items()}

        self.n_zones = len(self.zone2idx)
        self.n_hours = len(self.hour2idx)
        self.n_tokens = self.n_zones * self.n_hours
        self.n_classes = len(self.class2idx)

        if day_range is not None:
            df = df_all[df_all["일차"].between(day_range[0], day_range[1])].copy()
        else:
            df = df_all.copy()

        self.days = sorted(df["일차"].unique())
        self.day2idx = {d: i for i, d in enumerate(self.days)}

        self.window_size = window_size
        self.horizon = horizon

        self.grid_raw, self.target_raw = self._build_grid(df)

        if stats is None:
            self.stats = self._fit_stats(self.grid_raw)
        else:
            self.stats = stats

        self.grid = self._normalize(self.grid_raw, self.stats)

        max_start = len(self.days) - window_size - horizon + 1
        self.indices = list(range(max(0, max_start)))

    def _token_idx(self, zone_id, hour):
        z = self.zone2idx[zone_id]
        h = self.hour2idx[hour]
        return z * self.n_hours + h

    def _build_grid(self, df):
        D = len(self.days)
        N = self.n_tokens
        F = self.N_FEATURES

        grid = np.zeros((D, N, F), dtype=np.float32)
        target = np.zeros((D, N), dtype=np.float32)

        daily_total_purchase = df.groupby("일차").size().to_dict()

        for (day, zone_id, hour), grp in df.groupby(["일차", "구역ID", "hour"]):
            if day not in self.day2idx:
                continue

            d = self.day2idx[day]
            n = self._token_idx(zone_id, hour)

            purchase_count = len(grp)
            buyer_count = grp["에이전트ID"].nunique()
            dwell_mean = grp["체류시간"].mean()
            price_mean = grp["가격"].mean()

            daily_total = daily_total_purchase.get(day, 1)
            conversion_proxy = purchase_count / daily_total

            grid[d, n, 0] = purchase_count
            grid[d, n, 1] = buyer_count
            grid[d, n, 2] = dwell_mean
            grid[d, n, 3] = price_mean

            class_counts = grp["고객분류"].value_counts()
            for cls, cnt in class_counts.items():
                if cls in self.class2idx:
                    ci = self.class2idx[cls]
                    if ci < 4:
                        grid[d, n, 4 + ci] = cnt / purchase_count

            grid[d, n, 8] = conversion_proxy
            grid[d, n, 10] = ((day - 1) % 7) / 6.0

            target[d, n] = conversion_proxy

        # lag feature: 전날 동일 구역×시간대 구매건수
        for d in range(D):
            if d > 0:
                grid[d, :, 9] = grid[d - 1, :, 0]
            else:
                grid[d, :, 9] = 0

        return grid, target

    @staticmethod
    def _fit_stats(grid):
        flat = grid.reshape(-1, grid.shape[-1])

        means = flat.mean(axis=0)
        stds = flat.std(axis=0) + 1e-6

        # 비율형 feature는 정규화하지 않음
        ratio_cols = [4, 5, 6, 7, 8, 10]
        for c in ratio_cols:
            means[c] = 0
            stds[c] = 1

        return {
            "means": means.astype(np.float32),
            "stds": stds.astype(np.float32)
        }

    @staticmethod
    def _normalize(grid, stats):
        return ((grid - stats["means"]) / stats["stds"]).astype(np.float32)

    def __len__(self):
        return len(self.indices)

    def __getitem__(self, idx):
        start = self.indices[idx]

        x = self.grid[start:start + self.window_size]
        y = self.target_raw[start + self.window_size]

        return torch.from_numpy(x), torch.from_numpy(y)

"""# 2. LSTM 모델 구성

2번 코드는 구역·시간대별 시계열 패턴을 학습하기 위한 LSTM 모델을 정의하는 부분이다. Transformer 모델이 attention을 이용해 구역과 시간대 간 관계를 학습했다면, 본 모델은 각 구역·시간대 token의 최근 7일 흐름을 LSTM을 통해 학습하도록 설계하였다. 구역ID와 시간대 정보는 embedding layer를 통해 벡터로 변환한 뒤 기존 feature와 결합된다. 이후 각 구역·시간대별 sequence를 LSTM에 입력하여 시간적 변화 패턴을 학습하고, 마지막 시점의 hidden state를 이용해 다음 날의 구매비중을 예측한다. 출력층에는 sigmoid 함수를 사용하여 예측값이 0과 1 사이의 비율값으로 나오도록 하였다.
"""

# =========================================================
# 2. Model
# Zone-Hour Temporal LSTM
# =========================================================

class ZoneHourLSTM(nn.Module):
    """
    Transformer처럼 구역×시간대 token 구조를 유지하되,
    attention 대신 각 token의 시간 흐름을 LSTM으로 학습.
    """

    def __init__(self, n_zones, n_hours, n_features,
                 hidden_size=128, num_layers=2, dropout=0.2):
        super().__init__()

        self.n_zones = n_zones
        self.n_hours = n_hours
        self.n_tokens = n_zones * n_hours

        self.zone_emb = nn.Embedding(n_zones, 16)
        self.hour_emb = nn.Embedding(n_hours, 16)

        input_size = n_features + 16 + 16

        self.lstm = nn.LSTM(
            input_size=input_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            batch_first=True,
            dropout=dropout
        )

        self.head = nn.Sequential(
            nn.Linear(hidden_size, hidden_size // 2),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_size // 2, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        """
        x: [B, L, N, F]
        output: [B, N]
        """
        B, L, N, F = x.shape

        device = x.device

        zone_ids = torch.arange(self.n_zones, device=device).repeat_interleave(self.n_hours)
        hour_ids = torch.arange(self.n_hours, device=device).repeat(self.n_zones)

        z_emb = self.zone_emb(zone_ids)
        h_emb = self.hour_emb(hour_ids)

        token_emb = torch.cat([z_emb, h_emb], dim=-1)
        token_emb = token_emb.unsqueeze(0).unsqueeze(0)
        token_emb = token_emb.expand(B, L, N, -1)

        x = torch.cat([x, token_emb], dim=-1)

        # token별 시간 sequence로 변환
        # [B, L, N, F] -> [B*N, L, F]
        x = x.permute(0, 2, 1, 3).contiguous()
        x = x.view(B * N, L, -1)

        out, _ = self.lstm(x)

        last = out[:, -1, :]
        pred = self.head(last).squeeze(-1)

        pred = pred.view(B, N)

        return pred

"""# 3. Dataset 및 DataLoader 생성

3번 코드는 전체 데이터를 학습용, 검증용, 테스트용으로 나누고 DataLoader를 생성하는 과정이다. 데이터는 시간 순서를 유지한 상태에서 train, validation, test set으로 분할하였다. 이는 미래 데이터를 이용해 과거를 예측하는 데이터 누수를 방지하기 위한 방식이다. train set에서 생성한 구역, 시간대, 고객분류 mapping과 정규화 통계값을 validation/test set에도 동일하게 적용하여 세 데이터셋의 입력 구조가 일관되도록 하였다. 이후 PyTorch의 DataLoader를 사용하여 mini-batch 단위로 데이터를 모델에 공급할 수 있도록 구성하였다.
"""

# =========================================================
# 3. Dataset / DataLoader
# =========================================================

df_check = pd.read_csv(PURCHASE_CSV)
max_day = df_check["일차"].max()

train_end = CFG["train_days"]
val_end = train_end + CFG["val_days"]
test_start = val_end + 1

train_ds = ZoneHourConversionDataset(
    PURCHASE_CSV,
    window_size=CFG["window_size"],
    horizon=CFG["horizon"],
    day_range=(1, train_end)
)

val_ds = ZoneHourConversionDataset(
    PURCHASE_CSV,
    window_size=CFG["window_size"],
    horizon=CFG["horizon"],
    day_range=(train_end + 1, val_end),
    stats=train_ds.stats,
    zone2idx=train_ds.zone2idx,
    hour2idx=train_ds.hour2idx,
    class2idx=train_ds.class2idx
)

test_ds = ZoneHourConversionDataset(
    PURCHASE_CSV,
    window_size=CFG["window_size"],
    horizon=CFG["horizon"],
    day_range=(test_start, max_day),
    stats=train_ds.stats,
    zone2idx=train_ds.zone2idx,
    hour2idx=train_ds.hour2idx,
    class2idx=train_ds.class2idx
)

train_loader = DataLoader(train_ds, batch_size=CFG["batch_size"], shuffle=True)
val_loader = DataLoader(val_ds, batch_size=CFG["batch_size"], shuffle=False)
test_loader = DataLoader(test_ds, batch_size=CFG["batch_size"], shuffle=False)

print("Train:", len(train_ds))
print("Val:", len(val_ds))
print("Test:", len(test_ds))

x0, y0 = train_ds[0]
print("x shape:", x0.shape)
print("y shape:", y0.shape)

print("zones:", train_ds.n_zones)
print("hours:", train_ds.n_hours)
print("tokens:", train_ds.n_tokens)

"""# 4. 모델 학습

4번 코드는 Zone-Hour LSTM 모델을 실제로 학습시키는 과정이다. 손실함수로는 SmoothL1Loss를 사용하였으며, 이는 MSE보다 이상치에 덜 민감하면서도 안정적으로 회귀 문제를 학습할 수 있다는 장점이 있다. Optimizer는 AdamW를 사용하여 weight decay를 함께 적용하였고, gradient clipping을 통해 학습 중 gradient가 과도하게 커지는 문제를 방지하였다. 또한 validation loss가 더 이상 개선되지 않을 경우 학습률을 줄이는 ReduceLROnPlateau scheduler를 적용하였다. 학습 과정에서는 validation loss가 가장 낮은 모델을 저장하여 최종 평가에 사용하도록 하였다.
"""

# =========================================================
# 4. Train
# =========================================================

model = ZoneHourLSTM(
    n_zones=train_ds.n_zones,
    n_hours=train_ds.n_hours,
    n_features=ZoneHourConversionDataset.N_FEATURES,
    hidden_size=CFG["hidden_size"],
    num_layers=CFG["num_layers"],
    dropout=CFG["dropout"]
).to(device)

criterion = nn.SmoothL1Loss(beta=0.5)

optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=CFG["lr"],
    weight_decay=CFG["weight_decay"]
)

scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer,
    mode="min",
    factor=0.5,
    patience=10
)

best_val = float("inf")
no_improve = 0

train_losses = []
val_losses = []

for epoch in range(1, CFG["epochs"] + 1):
    model.train()
    train_loss = 0

    for x, y in train_loader:
        x = x.to(device)
        y = y.to(device)

        optimizer.zero_grad()

        pred = model(x)
        loss = criterion(pred, y)

        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()

        train_loss += loss.item() * x.size(0)

    train_loss /= len(train_loader.dataset)

    model.eval()
    val_loss = 0

    with torch.no_grad():
        for x, y in val_loader:
            x = x.to(device)
            y = y.to(device)

            pred = model(x)
            loss = criterion(pred, y)

            val_loss += loss.item() * x.size(0)

    val_loss /= len(val_loader.dataset)

    scheduler.step(val_loss)

    train_losses.append(train_loss)
    val_losses.append(val_loss)

    if val_loss < best_val:
        best_val = val_loss
        no_improve = 0

        torch.save({
            "model_state": model.state_dict(),
            "stats": train_ds.stats,
            "zone2idx": train_ds.zone2idx,
            "hour2idx": train_ds.hour2idx,
            "class2idx": train_ds.class2idx,
            "cfg": CFG,
        }, "best_zone_hour_lstm.pt")
    else:
        no_improve += 1

    if epoch % 10 == 0:
        lr = optimizer.param_groups[0]["lr"]
        print(
            f"Epoch {epoch:03d} | "
            f"Train {train_loss:.6f} | "
            f"Val {val_loss:.6f} | "
            f"LR {lr:.6f}"
        )

    if no_improve >= CFG["patience"]:
        print("Early stopping")
        break

"""# 5. Loss 시각화

5번 코드는 학습 과정에서 기록된 train loss와 validation loss를 그래프로 시각화하는 부분이다. 이를 통해 모델이 학습이 진행됨에 따라 손실이 안정적으로 감소하는지, validation loss가 특정 시점 이후 증가하여 과적합이 발생하는지 확인할 수 있다. 본 모델의 경우 train loss와 validation loss가 전반적으로 함께 감소하는 경향을 보였으며, validation loss가 급격히 증가하지 않았기 때문에 심한 과적합은 발생하지 않은 것으로 판단할 수 있다.
"""

# =========================================================
# 5. Loss Plot
# =========================================================

plt.figure(figsize=(8, 4))
plt.plot(train_losses, label="Train Loss")
plt.plot(val_losses, label="Val Loss")
plt.xlabel("Epoch")
plt.ylabel("SmoothL1 Loss")
plt.title("Zone-Hour LSTM Training Curve")
plt.legend()
plt.grid(alpha=0.3)
plt.show()

"""# 6. Test Evaluation

6번 코드는 학습 과정에서 validation loss가 가장 낮았던 최적 모델을 불러와 test set에서 최종 성능을 평가하는 부분이다. 저장된 checkpoint에서 모델 가중치를 불러오고, test_loader에 있는 데이터를 이용해 예측값과 실제값을 수집한다. 이후 MAE, RMSE, MAPE, sMAPE 지표를 계산하여 모델의 예측 성능을 정량적으로 평가한다. MAE와 RMSE는 예측값과 실제값의 평균적인 오차 크기를 보여주며, MAPE와 sMAPE는 비율 기반 오차를 확인하는 데 사용된다. 이를 통해 모델이 학습 데이터뿐만 아니라 새로운 test 데이터에서도 얼마나 안정적으로 예측하는지 확인할 수 있다.
"""

# =========================================================
# 6. Test Evaluation
# =========================================================

from sklearn.metrics import mean_absolute_error, mean_squared_error

ckpt = torch.load(
    "best_zone_hour_lstm.pt",
    map_location=device,
    weights_only=False
)

model.load_state_dict(ckpt["model_state"])
model.eval()

preds = []
trues = []

with torch.no_grad():
    for x, y in test_loader:
        x = x.to(device)

        pred = model(x).cpu().numpy()

        preds.append(pred)
        trues.append(y.numpy())

preds = np.concatenate(preds, axis=0)
trues = np.concatenate(trues, axis=0)

# ===== metrics =====
mae = mean_absolute_error(trues.flatten(), preds.flatten())
rmse = np.sqrt(mean_squared_error(trues.flatten(), preds.flatten()))

mask = trues > 1e-6
mape = np.mean(np.abs((preds[mask] - trues[mask]) / trues[mask])) * 100

smape = np.mean(
    2 * np.abs(preds - trues) /
    (np.abs(preds) + np.abs(trues) + 1e-6)
) * 100

print("===== Test Result: Zone-Hour LSTM =====")
print(f"MAE   : {mae:.6f}")
print(f"RMSE  : {rmse:.6f}")
print(f"MAPE  : {mape:.2f}%")
print(f"sMAPE : {smape:.2f}%")

"""# 7. Persistence Baseline 비교

7번 코드는 LSTM 모델의 성능을 단순 기준 모델인 Persistence Baseline과 비교하는 과정이다. Persistence Baseline은 전날의 구역·시간대별 구매비중이 다음 날에도 동일하게 유지된다고 가정하는 단순 예측 방식이다. 이 baseline은 시계열 예측 문제에서 최소한으로 넘어서야 하는 기준 성능으로 활용된다. LSTM 모델의 MAE와 RMSE를 baseline의 MAE, RMSE와 비교하여 개선율을 계산함으로써, 모델이 단순히 전날 값을 복사하는 수준을 넘어 실제 시계열 패턴을 학습했는지 평가할 수 있다.
"""

# =========================================================
# 7. Persistence Baseline
# =========================================================

baseline_preds = []
baseline_trues = []

for i in range(len(test_ds)):
    x, y = test_ds[i]

    # 전날 값 그대로 예측
    last_day_share = x[-1, :, 8].numpy()

    baseline_preds.append(last_day_share)
    baseline_trues.append(y.numpy())

baseline_preds = np.array(baseline_preds)
baseline_trues = np.array(baseline_trues)

# ===== baseline metrics =====
base_mae = mean_absolute_error(
    baseline_trues.flatten(), baseline_preds.flatten()
)
base_rmse = np.sqrt(mean_squared_error(
    baseline_trues.flatten(), baseline_preds.flatten()
))

mask = baseline_trues > 1e-6
base_mape = np.mean(
    np.abs((baseline_preds[mask] - baseline_trues[mask]) / baseline_trues[mask])
) * 100

base_smape = np.mean(
    2 * np.abs(baseline_preds - baseline_trues) /
    (np.abs(baseline_preds) + np.abs(baseline_trues) + 1e-6)
) * 100

print("===== Persistence Baseline =====")
print(f"MAE   : {base_mae:.6f}")
print(f"RMSE  : {base_rmse:.6f}")
print(f"MAPE  : {base_mape:.2f}%")
print(f"sMAPE : {base_smape:.2f}%")

# ===== improvement =====
print("\n===== Improvement =====")

if base_mae > 0:
    print(f"MAE improvement  : {(base_mae - mae) / base_mae * 100:.2f}%")
else:
    print("MAE improvement  : 계산 불가")

if base_rmse > 0:
    print(f"RMSE improvement : {(base_rmse - rmse) / base_rmse * 100:.2f}%")
else:
    print("RMSE improvement : 계산 불가")

"""# 8. 시간대 KPI 비교

8번 코드는 구역·시간대 단위로 예측된 결과를 시간대 기준으로 집계하여 실제값과 예측값을 비교하는 부분이다. 모델은 구역×시간대 token 단위로 예측을 수행하지만, 최종 KPI 해석을 위해 각 시간대별로 모든 구역의 구매비중을 합산하였다. 이를 통해 하루 중 어느 시간대의 구매비중이 높게 나타나는지, 모델이 시간대별 구매 패턴을 잘 예측했는지 확인할 수 있다. 결과는 표와 선 그래프로 시각화되며, 실제 시간대별 구매비중과 예측 구매비중의 차이를 직관적으로 비교할 수 있다. 이 분석은 매장의 시간대별 상품 배치, 프로모션 운영, 인력 배치 전략 수립에 활용될 수 있다.
"""

# =========================================================
# 8. 시간대 KPI
# =========================================================

Z = test_ds.n_zones
T = test_ds.n_hours
hours = [test_ds.idx2hour[i] for i in range(T)]

pred_grid = preds.reshape(-1, Z, T)
true_grid = trues.reshape(-1, Z, T)

hour_pred = pred_grid.sum(axis=1).mean(axis=0)
hour_true = true_grid.sum(axis=1).mean(axis=0)

import pandas as pd

hour_result_df = pd.DataFrame({
    "시간대": [f"{h}시" for h in hours],
    "실제": hour_true,
    "예측": hour_pred,
    "오차": np.abs(hour_true - hour_pred)
})

display(hour_result_df)

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 4))
plt.plot(hours, hour_true, marker="o", label="True")
plt.plot(hours, hour_pred, marker="o", label="Pred")
plt.legend()
plt.grid(alpha=0.3)
plt.title("Hourly KPI")
plt.show()

df = pd.read_csv(PURCHASE_CSV)

df["hour"] = df["시간대"].str.replace("시", "").astype(int)

kpi_hour = df.groupby(["일차", "hour"]).agg(
    purchase_count=("에이전트ID", "count"),
    buyer_count=("에이전트ID", "nunique"),
    avg_dwell=("체류시간", "mean"),
    avg_price=("가격", "mean")
).reset_index()

daily_total = kpi_hour.groupby("일차")["purchase_count"].transform("sum")
kpi_hour["conversion_proxy"] = kpi_hour["purchase_count"] / daily_total

kpi_hour.to_csv("hour_kpi.csv", index=False)

"""구매비중이 가장 높은 시간대는:

13시: 0.1106
14시: 0.1082
15시: 0.0988
18시: 0.0962
17시: 0.0922

반대로 낮은 시간대는:

10시: 0.0490
21시: 0.0523
11시: 0.0644
20시: 0.0659
"""